### ISSUE TITLE
Can't Publish with SampleDevice

### ISSUE THREAD

**Issue by ssudhe** [ibm-watson-iot/iot-embeddedc#20] opened 2016-08-24 04:57 UTC
I ran the ./setup.sh & make in the samples.
and i dont see the device publishing anything. 
Can you please let me know what may be missing. When adding the device, I did note the values as below when adding my device and added them in the device.cfg
org=rgcggg
type=iotsample-devicetype
id=9900114850ab
auth-method=token
auth-token=mz2lh*Da_l0e07R9*k

linaro@linaro-gnome:~/test/iot-embeddedc/samples$ ./sampleDevice
Connecting to registered service with org rgcggg

I also tested on ubuntu 14.04 & the behavior is the same. The terminal hangs. I think the client initialization fails. Anything wrong in adding the device in the Bluemix

I checked if firewall is blocking, but the telent tests is OK.
 telnet rgcggg.messaging.internetofthings.ibmcloud.com 8883
Trying 169.45.2.20...
Connected to us.messaging.internetofthings.ibmcloud.com.
Escape character is '^]'.

**Comment by phariprasadreddy** [comment] 2016-08-24 08:59
@ssudhe you have done correctly for setting up the client library and building the samples.
I have tried here the same steps and it built all the samples.
I have tried with your device.cfg details it is not connecting from my side. It looks like the problem is with the device configuration details. I was able to connect and publish events with my credentials. 
One more point to mention quickstart is working fine without any issues. 
Please let me know if you have any queries.

**Comment by ssudhe** [comment] 2016-08-24 09:22
Thanks for you response.
I just created a device as per the below link
https://developer.ibm.com/recipes/tutorials/how-to-register-devices-in-ibm-iot-foundation/

Below in the cfg in the device.cfg but still see the issue.
org=bucvda
type=qciot-device-type
id=qcdevice01
auth-method=token
auth-token=qcinnovation

Can you please provide me a test configuration if any that works for you. If not, what steps might have gone missing in creating the device & getting the config details.
Regards,
Shubha

**Comment by phariprasadreddy** [comment] 2016-08-24 10:17
@ssudhe With the config details shared above it is working fine. Please share the logs.

**Comment by ssudhe** [comment] 2016-08-24 10:26
I don't see any logs except the below. Any other ways of collecting more logs
> ./sampleDevice
Connecting to registered service with org bucvda

For Quickstart,
> ./helloWorld 123asdqwer456 

may be network firewall issue. Any other steps to check this other than the telnet command that i used above

**Comment by phariprasadreddy** [comment] 2016-08-24 11:43
@ssudhe while executing the control will return after connectiotf() in sampleDevice.c. Try to print out rc after this. And also add more logs in src/iotfClient.c in the function connectiotf(). This will give us more details.

On the other side you can try Java Client library or Nodejs library.

**Comment by ssudhe** [comment] 2016-08-25 11:25
Thanks for helping verify the device credentials & the support. As guessed, the issue was due to the network. I connected the device to a different network and the helloworld & the sampleDevice works .I was able to see the connection on the dashboard.

Regards,
Shubha

**Comment by phariprasadreddy** [comment] 2016-08-25 11:30
As it is working I am closing the issue.

**Closed by phariprasadreddy** 2016-08-25 11:30 UTC
